<?php

return [
    'sales' => [
        'rounding_account' => [
            'code' => '7000007',
            'name' => 'Pembulatan',
        ],
        'payment_accounts' => [
            'online_delivery' => [
                'code' => '1102015',
                'name' => 'Gofood',
                'methods' => ['credit_card', 'debit_card', 'go_food', 'gofood', 'go_pay', 'gopay', 'grab_food', 'grabfood', 'qris'],
            ],
            'ovo' => [
                'code' => '1102016',
                'name' => 'Grab',
                'methods' => ['ovo'],
            ],
            'shopee' => [
                'code' => '1102017',
                'name' => 'Shopee',
                'methods' => ['shopee_food', 'shopeefood', 'shopee_pay', 'shopeepay'],
            ],
        ],
        'outlet_mappings' => [
            [
                'alias_voucher' => 'CP',
                'sales_coa_code' => '4101001',
                'sales_coa_name' => 'Penjualan CP',
                'cashbank_coa_code' => '1102001',
                'cashbank_coa_name' => 'Bri Central',
                'discount_coa_code' => '5103001',
                'discount_coa_name' => 'Disc Penjualan CP',
                'meal_coa_code' => '5505001',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto CP',
                'match' => ['cp', 'central plaza', 'Ransa central plaza', 'out02'],
            ],
            [
                'alias_voucher' => 'CPZ',
                'sales_coa_code' => '4101002',
                'sales_coa_name' => 'Penjualan Ciplaz',
                'cashbank_coa_code' => '1102003',
                'cashbank_coa_name' => 'Bri Ciplaz',
                'discount_coa_code' => '5103002',
                'discount_coa_name' => 'Disc Penjualan Ciplaz',
                'meal_coa_code' => '5505002',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto Ciplaz',
                'match' => ['ciplaz', 'cpz'],
            ],
            [
                'alias_voucher' => 'LC1',
                'sales_coa_code' => '4101003',
                'sales_coa_name' => 'Penjualan karang Indah Mall',
                'cashbank_coa_code' => '1102004',
                'cashbank_coa_name' => 'Bri Lampung City 1',
                'discount_coa_code' => '5103003',
                'discount_coa_name' => 'Disc Penjualan karang Indah mall',
                'meal_coa_code' => '5505003',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto BC',
                'match' => ['lc1', 'lampungcity1'],
            ],
            [
                'alias_voucher' => 'LC2',
                'sales_coa_code' => '4101004',
                'sales_coa_name' => 'Penjualan Lampung City 2',
                'cashbank_coa_code' => '1102005',
                'cashbank_coa_name' => 'Bri Lampung City 2',
                'discount_coa_code' => '5103004',
                'discount_coa_name' => 'Disc Penjualan Lampung City 2',
                'meal_coa_code' => '5505004',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto LC 2',
                'match' => ['lc2', 'lampungcity2'],
            ],
            [
                'alias_voucher' => 'PHM',
                'sales_coa_code' => '4101005',
                'sales_coa_name' => 'Penjualan Pahoman',
                'cashbank_coa_code' => '1102006',
                'cashbank_coa_name' => 'Bri Pahoman',
                'discount_coa_code' => '5103005',
                'discount_coa_name' => 'Disc Penjualan Pahoman',
                'meal_coa_code' => '5505005',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto Pahoman',
                'match' => ['pahoman', 'phm'],
            ],
            [
                'alias_voucher' => 'MBK1',
                'sales_coa_code' => '4101006',
                'sales_coa_name' => 'Penjualan Mbk 1',
                'cashbank_coa_code' => '1102007',
                'cashbank_coa_name' => 'Bri Mbk 1',
                'discount_coa_code' => '5103006',
                'discount_coa_name' => 'Disc Penjualan Mbk 1',
                'meal_coa_code' => '5505006',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto Mbk 1',
                'match' => ['mbk1'],
            ],
            [
                'alias_voucher' => 'MBK2',
                'sales_coa_code' => '4101007',
                'sales_coa_name' => 'Penjualan Mbk 2',
                'cashbank_coa_code' => '1102008',
                'cashbank_coa_name' => 'Bri Mbk 2',
                'discount_coa_code' => '5103007',
                'discount_coa_name' => 'Disc Penjualan Mbk 2',
                'meal_coa_code' => '5505007',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto Mbk 2',
                'match' => ['mbk2'],
            ],
            [
                'alias_voucher' => 'MKT',
                'sales_coa_code' => '4101008',
                'sales_coa_name' => 'Penjualan Mall Kartini',
                'cashbank_coa_code' => '1102009',
                'cashbank_coa_name' => 'Bri Mall Kartini',
                'discount_coa_code' => '5103008',
                'discount_coa_name' => 'Disc Penjualan Mall Kartini',
                'meal_coa_code' => '5505008',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto Moka',
                'match' => ['mallkartini', 'mkt', 'moka'],
            ],
            [
                'alias_voucher' => 'CM',
                'sales_coa_code' => '4101009',
                'sales_coa_name' => 'Penjualan Chandra Metro',
                'cashbank_coa_code' => '1102010',
                'cashbank_coa_name' => 'Bri Chandra Metro',
                'discount_coa_code' => '5103009',
                'discount_coa_name' => 'Disc Penjualan Chandra Metro',
                'meal_coa_code' => '5505009',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto CM',
                'match' => ['chandrametro', 'cm'],
            ],
            [
                'alias_voucher' => 'CTR',
                'sales_coa_code' => '4101010',
                'sales_coa_name' => 'Penjualan Reseller Dan Frencise',
                'cashbank_coa_code' => '1102001',
                'cashbank_coa_name' => 'Bri Central',
                'discount_coa_code' => '5103011',
                'discount_coa_name' => 'DISC PENJUALAN TRANSMART',
                'meal_coa_code' => '5505010',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto',
                'match' => ['central', 'gudang', 'reseller', 'frenchsie', 'frencise'],
            ],
            [
                'alias_voucher' => 'TRM',
                'sales_coa_code' => '4101011',
                'sales_coa_name' => 'PENJUALAN TRANSMART',
                'cashbank_coa_code' => '1102013',
                'cashbank_coa_name' => 'BRI TRANSMART',
                'discount_coa_code' => '5103011',
                'discount_coa_name' => 'DISC PENJUALAN TRANSMART',
                'meal_coa_code' => '5505011',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto Transmart',
                'match' => ['transmart', 'trm', 'bri transmart'],
            ],
            [
                'alias_voucher' => 'CP2',
                'sales_coa_code' => '4101012',
                'sales_coa_name' => 'Penjualan CP 2',
                'cashbank_coa_code' => '1102014',
                'cashbank_coa_name' => 'Bri CP2',
                'discount_coa_code' => '5103001',
                'discount_coa_name' => 'Disc Penjualan CP 2',
                'meal_coa_code' => '5505012',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto CP2',
                'match' => ['cp2'],
            ],
            [
                'alias_voucher' => 'CKG',
                'sales_coa_code' => '4101013',
                'sales_coa_name' => 'Penjualan Chandra Karang',
                'cashbank_coa_code' => '1102018',
                'cashbank_coa_name' => 'Bank Chandra Karang',
                'discount_coa_code' => '5103013',
                'discount_coa_name' => 'Disc Penjualan Chandra Karang',
                'meal_coa_code' => '5505013',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto CHANDRA KARANG',
                'match' => ['chandrakarang', 'ckg'],
            ],
            [
                'alias_voucher' => 'PRG',
                'sales_coa_code' => '4101014',
                'sales_coa_name' => 'Penjualan Pringsewu',
                'cashbank_coa_code' => '1102001',
                'cashbank_coa_name' => 'Bri Central',
                'discount_coa_code' => '5103014',
                'discount_coa_name' => 'Disc Penjualan Pringsewu',
                'meal_coa_code' => '5505014',
                'meal_coa_name' => 'By Meal & Persediaan Rusak Resto Pringsewu',
                'match' => ['pringsewu', 'prg'],
            ],
        ],
    ],
    'hpp' => [
        'outlet_mappings' => [
            [
                'alias_voucher' => 'CP',
                'hpp_coa_code' => '5101001',
                'hpp_coa_name' => 'Hpp Makanan CP',
                'inventory_coa_code' => '1117002',
                'inventory_coa_name' => 'Persediaan Barang Dagang CP',
                'match' => ['cp', 'central plaza', 'Ransa central plaza', 'out02'],
            ],
            [
                'alias_voucher' => 'CPZ',
                'hpp_coa_code' => '5101002',
                'hpp_coa_name' => 'Hpp Makanan Ciplaz',
                'inventory_coa_code' => '1117003',
                'inventory_coa_name' => 'Persediaan Barang Dagang Ciplaz',
                'match' => ['ciplaz', 'cpz'],
            ],
            [
                'alias_voucher' => 'LC1',
                'hpp_coa_code' => '5101003',
                'hpp_coa_name' => 'Hpp Makanan LC1',
                'inventory_coa_code' => '1117004',
                'inventory_coa_name' => 'Persediaan Barang Dagang Lampung City 1',
                'match' => ['lc1', 'lampungcity1'],
            ],
            [
                'alias_voucher' => 'LC2',
                'hpp_coa_code' => '5101004',
                'hpp_coa_name' => 'Hpp Makanan Lampung City 2',
                'inventory_coa_code' => '1117005',
                'inventory_coa_name' => 'Persediaan Barang Dagang Lampung City 2',
                'match' => ['lc2', 'lampungcity2'],
            ],
            [
                'alias_voucher' => 'PHM',
                'hpp_coa_code' => '5101005',
                'hpp_coa_name' => 'Hpp Makanan Pahoman',
                'inventory_coa_code' => '1117006',
                'inventory_coa_name' => 'Persediaan Barang Dagang Pahoman',
                'match' => ['pahoman', 'phm'],
            ],
            [
                'alias_voucher' => 'MBK1',
                'hpp_coa_code' => '5101006',
                'hpp_coa_name' => 'Hpp Makanan Mbk 1',
                'inventory_coa_code' => '1117007',
                'inventory_coa_name' => 'Persediaan Barang Dagang Mbk 1',
                'match' => ['mbk1'],
            ],
            [
                'alias_voucher' => 'MBK2',
                'hpp_coa_code' => '5101007',
                'hpp_coa_name' => 'Hpp Makanan Mbk 2',
                'inventory_coa_code' => '1117008',
                'inventory_coa_name' => 'Persediaan Barang Dagang Mbk 2',
                'match' => ['mbk2'],
            ],
            [
                'alias_voucher' => 'MKT',
                'hpp_coa_code' => '5101008',
                'hpp_coa_name' => 'Hpp Makanan Mall Kartini',
                'inventory_coa_code' => '1117009',
                'inventory_coa_name' => 'Persediaan Barang Dagang Mall Kartini',
                'match' => ['mallkartini', 'mkt', 'moka'],
            ],
            [
                'alias_voucher' => 'CM',
                'hpp_coa_code' => '5101009',
                'hpp_coa_name' => 'Hpp Makanan Chandra Metro',
                'inventory_coa_code' => '1117010',
                'inventory_coa_name' => 'Persediaan Barang Dagang Chandra Metro',
                'match' => ['chandrametro', 'cm'],
            ],
            [
                'alias_voucher' => 'CTR',
                'hpp_coa_code' => '5101010',
                'hpp_coa_name' => 'Hpp Makanan Reseller Dan Frencise',
                'inventory_coa_code' => '1117001',
                'inventory_coa_name' => 'Persediaan Barang Dagang Central',
                'match' => ['central', 'gudang', 'reseller', 'frenchsie', 'frencise'],
            ],
            [
                'alias_voucher' => 'TRM',
                'hpp_coa_code' => '5101011',
                'hpp_coa_name' => 'Hpp Makanan Transmart',
                'inventory_coa_code' => '1117011',
                'inventory_coa_name' => 'Persediaan Barang Dagang Transmart',
                'match' => ['transmart', 'trm', 'bri transmart'],
            ],
            [
                'alias_voucher' => 'CP2',
                'hpp_coa_code' => '5101012',
                'hpp_coa_name' => 'Hpp Makanan CP 2',
                'inventory_coa_code' => '1117012',
                'inventory_coa_name' => 'Persediaan Barang Dagang CP 2',
                'match' => ['cp2'],
            ],
            [
                'alias_voucher' => 'CKG',
                'hpp_coa_code' => '5101013',
                'hpp_coa_name' => 'Hpp Makanan Chandra Karang',
                'inventory_coa_code' => '1117013',
                'inventory_coa_name' => 'Persediaan Barang Dagang Chandra Karang',
                'match' => ['chandrakarang', 'ckg'],
            ],
            [
                'alias_voucher' => 'PRG',
                'hpp_coa_code' => '5101014',
                'hpp_coa_name' => 'Hpp Makanan Pringsewu',
                'inventory_coa_code' => '1117014',
                'inventory_coa_name' => 'Persediaan Barang Dagang Pringsewu',
                'match' => ['pringsewu', 'prg'],
            ],
        ],
    ],
    'purchase' => [
        'default_ap_account' => [
            'code' => '2102020',
            'name' => 'Hutang Usaha Lain-lain',
        ],
        'supplier_ap_mappings' => [
            [
                'code' => '2102001',
                'name' => 'Hutang Usaha Amir Sayur',
                'match' => ['amir sayur', 'amirsayur'],
            ],
            [
                'code' => '2102002',
                'name' => 'Hutang Usaha Anugerah Jaya Sentosa',
                'match' => ['anugerah jaya sentosa', 'anugerahjayasentosa'],
            ],
            [
                'code' => '2102003',
                'name' => 'Hutang Usaha Anugerah Jaya Tjemerlang',
                'match' => ['anugerah jaya tjemerlang', 'anugerahjayatjemerlang'],
            ],
            [
                'code' => '2102004',
                'name' => 'Hutang Usaha Aroma',
                'match' => ['aroma'],
            ],
            [
                'code' => '2102005',
                'name' => 'Hutang Usaha Ayam Jangkung',
                'match' => ['ayam jangkung', 'ayamjangkung'],
            ],
            [
                'code' => '2102006',
                'name' => 'Hutang Usaha Belanja',
                'match' => ['belanja'],
            ],
            [
                'code' => '2102007',
                'name' => 'Hutang Usaha Cedea',
                'match' => ['cedea'],
            ],
            [
                'code' => '2102008',
                'name' => 'Hutang Usaha Central Kitchen',
                'match' => ['central kitchen', 'centralkitchen'],
            ],
            [
                'code' => '2102009',
                'name' => 'Hutang Usaha Gemilang Kencana Makmur',
                'match' => ['gemilang kencana makmur', 'gemilangkencanamakmur'],
            ],
            [
                'code' => '2102010',
                'name' => 'Hutang Usaha Gudang',
                'match' => ['gudang'],
            ],
            [
                'code' => '2102011',
                'name' => 'Hutang Usaha Indoyasa',
                'match' => ['indoyasa'],
            ],
            [
                'code' => '2102012',
                'name' => 'Hutang Usaha Lokatara',
                'match' => ['lokatara'],
            ],
            [
                'code' => '2102013',
                'name' => 'Hutang Usaha Mie Aming',
                'match' => ['mie aming', 'mieaming'],
            ],
            [
                'code' => '2102014',
                'name' => 'Hutang Usaha Mie Ayam',
                'match' => ['mie ayam', 'mieayam'],
            ],
            [
                'code' => '2102015',
                'name' => 'Hutang Usaha Nakama Packaging',
                'match' => ['nakama packaging', 'nakamapackaging'],
            ],
            [
                'code' => '2102016',
                'name' => 'Hutang Usaha Nestle',
                'match' => ['nestle'],
            ],
            [
                'code' => '2102017',
                'name' => 'Hutang Usaha Prima Frozen',
                'match' => ['prima frozen', 'primafrozen'],
            ],
            [
                'code' => '2102018',
                'name' => 'Hutang Usaha Pt Kopi Nusantara',
                'match' => ['pt kopi nusantara', 'kopi nusantara', 'ptkopinusantara', 'kopinusantara'],
            ],
            [
                'code' => '2102019',
                'name' => 'Hutang Usaha Pt. Elpinas',
                'match' => ['pt elpinas', 'elpinas', 'ptelpinas'],
            ],
        ],
    ],
];


